version: '3.7'

services:
  frontend:
    container_name: frontend-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - '.:/app'
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: