version: '3.7'

services:

  dev:
    container_name: blackspace-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      
  prod:
    container_name: blackspace-ui
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'