version: '3.7'
services:
    frontend-service:
      container_name: frontend-service
      build:
        context: .
        dockerfile: Dockerfile.prod
      ports:
          - "8000:80"
      labels:
          NAME: "frontend-service"
      networks:
          - net

networks:
    net:
        driver: bridge