apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      NAME: frontend-service
      kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest.yaml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
      io.kompose.service: frontend-service
    name: frontend-service
  spec:
    ports:
    - name: "8000"
      port: 8000
      targetPort: 80
    selector:
      io.kompose.service: frontend-service
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      NAME: frontend-service
      kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest.yaml
      kompose.version: 1.19.0 (f63a961c)
    creationTimestamp: null
    labels:
      io.kompose.service: frontend-service
    name: frontend-service
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        annotations:
          NAME: frontend-service
          kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest.yaml
          kompose.version: 1.19.0 (f63a961c)
        creationTimestamp: null
        labels:
          io.kompose.service: frontend-service
      spec:
        containers:
        - image: frontend-service
          name: frontend-service
          ports:
          - containerPort: 80
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

