# this file will build, run tests, and build on push and pull request 
name: Continuous Integration
#actions below will run for every push and pull request submitted to master or develop branch
on: 
#  Trigger the workflow on push or pull request,
#  but only for the master branch
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
  steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn # Extra Step
    - name: yarn install, build, and test
    run: |
      yarn install
      yarn run build
      yarn test
      
