# this file will build, run tests, and build on push and pull request 
name: Continuous Integration
#actions below will run for every push and pull request submitted to master or develop branch
on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
  steps:
    - uses: actions/checkout@v2
    - name: Checkout my-organization/awesome-action
      uses: actions/checkout@v2
      with:
        repository: BlackspaceInc/Frontend/.github/workflows/continuous-integration.yml
        ref: refs/heads/master
                    # GitHub's personal access token with access to `my-organization/awesome-action`
        token: $
        persist-credentials: false
        path: ./.github/workflows/continuous-integration.yml
        - uses: ./.github/workflows/continuous-integration.yml
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn # Extra Step
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
        yarn test
      
