# this file will build, run tests, and build on push and pull request 
name: Continuous Integration
#actions below will run for every push and pull request submitted to master or develop branch
on: 
#  Trigger the workflow on push or pull request,
#  but only for the master branch
  push:
    paths:
      - '**.js'
    branches:
      - master
      - develop
  pull_request:
    paths:
      - '**.js'
    branches:
      - master
      - develop
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: CultureHQ/actions-yarn@v1.0.1
      - name: Install Dependencies
        run: yarn
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Show version number
        run: echo "Version is ${{ steps.package-version.outputs.version }}"
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --watchAll=false
      
        
